android/8Bitdo FC30 GamePad.cfg

- Renamed file to match the other 8Bitdo autoconfig file names
- Added VID/PID
- Added display name
- Fixed SELECT button code

Update and rename FC30_Gamepad.cfg to 8Bitdo FC30 GamePad.cfg

---

android/NVIDIA_SHIELD_Gamepad.cfg

This is necessary after a fix was implemented for simultaneous button presses
in the Android input driver.
It might also be necessary to test the NVIDIA SHIELD Remote for the same
issue, but I don't have that myself.

Set menu toggle button to new keycode for NVIDIA SHIELD Controller.

---

udev/DragonRise_Inc.___Generic___USB__Joystick__.cfg

This configuration is for multiple controllers sharing the same USB
encoder.
Added button names for the most common naming of these gamepads.
Added information about the chip and controller variations sharing the
same USB ID.
Corrected mapping of right analog stick.

Updated DragonRise PID 6

---

udev/DragonRise Inc. Gamepad.cfg

There are three separate configuration files for Dragonrise 0079:0011.
Two of them used to have identical button mappings but one of them used
the VID:PID string "Dragonrise Inc. Gamepad" instead of the proper
iProduct string "USB Gamepad " as device_name.
This was corrected and button layout was changed to a more common layout
in that variant of the configuration file. 
note that this is yet another example of this issue:
https://github.com/libretro/RetroArch/issues/3914

udev: Updated Dragonrise 0079:0011

---

Makefile
configure

The `./configure` and `make` tasks allow the joypad configuration to be installed to the given `DESTDIR`. This will be used in FlatPak to allow packaging and distribution.

Add a Makefile

---

sdl2/X360 Controller.cfg

This adds a few device settings for the Xbox 360 controller allowing it to work autodetect under SDL2.

Fix Xbox 360 Controller for SDL2

---

hid/Mayflash_Wii_Classic_Controller_Adapter.cfg

This USB controller adapter has 2 ports and presents itself as 2 devices to Retroarch.
There seems to be a race on which port gets to be device `#0` and which gets to be device `#1`
http://www.mayflash.com/products/pcusb/pc052.html

hid: Add Mayflash Wii Classic Controller Adapter

---

udev/GameStick Controller.cfg

People might have this controller laying around like me, surprisingly it works good, but no R2/L2 buttons, also the select key is labelled back and sends a keyboard "backspace" so that needs to be mapped manually.  Also attached is the udev rule.  I can create a PR for that as well, but not sure where it goes (had to rename to .txt to attach).
[99-gamestick-controller.rules.txt](https://github.com/libretro/retroarch-joypad-autoconfig/files/2299096/99-gamestick-controller.rules.txt)

adding GameStick Controller config

---

hid/8Bitdo_NES30_Pro.cfg

Add support for 8Bitdo NES30 Pro. 
Notes:
* This is for the Android mode where you power on with no additional buttons pressed. It shows up as "8Bitdo NES30 Pro" this way.
* Works for both BT and USB
* Tested on the latest firmware as of now (4.10) as well as 4.01
* You can also start it up in macOS mode by holding A during power on, but then it spoofs as a DS4 controller and this config won't apply
* If you run it in this mode it makes RA segafult when exiting so I recommend running it in the default (Android) mode

hid: Add 8Bitdo NES30 Pro

---

hid/8Bitdo_SNES30_BT.cfg
hid/8Bitdo_SNES30_USB.cfg

Add support for 8Bitdo SNES30.
Notes:
* This is for the Android mode where you power on with no additional buttons pressed. It shows up as "8Bitdo SNES30 GamePad" this way.
* In USB it shows up as "SNES30 Joy   "
* Separate configs for BT and USB because the pid differs for each (same vid)
* Tested on the latest firmware as of now (4.10)
* Not sure if it makes a difference, but this was tested on a model prior to the rebranding to SN30

hid: Add 8Bitdo SNES30

---

hid/8Bitdo_SN30_Pro.cfg

Add support for 8Bitdo SN30 Pro.
Notes:
* This is for the Android mode where you power on with no additional buttons pressed. It shows up as "8Bitdo SN30 Pro" this way.
* Works for both BT and USB
* Tested on the latest firmware as of now (1.29)

hid: Add 8Bitdo SN30 Pro

---

udev/Retrode Mega Drive _1.cfg
udev/Retrode Mega Drive _2.cfg
udev/Retrode SNES _ N64 _1.cfg
udev/Retrode SNES _ N64 _2.cfg
xinput/Retrode_2.cfg

I saved the autoconfig files on Linux, so the `input_device` names were automatically detected.
Then added labels.

Add Retrode files for Linux

---

README.md

A while time ago @CoalaJoe created an [issue](https://github.com/libretro/retroarch-joypad-autoconfig/issues/322) with the idea of creating a README file for the project. @hizzlekizzle was positive about the idea but it seems nobody created a PR to deal with that.
Recently I've spent some time dealing with issues inside autoconfig profile files and I learned a bit about how things work. So I wanted to contribute to the project writing down some useful bits of documentation around autoconfig profiles.
I hope you find this useful, let me know what do you think.

Propose README.md file including some useful documentation about the project

---

android/Defender_Game_Racer_Classic.cfg
android/GPD_Q9.cfg
dinput/DragonRise_Inc.___Generic___USB__Joystick__.cfg
udev/DIALOG_GP-A11.cfg
udev/DragonRise Inc. Gamepad.cfg
udev/DragonRise_Inc.___Generic___USB__Joystick__.cfg
udev/DragonRise_X-Box_Gamepad_with_Force_Feedback.cfg
udev/Gametel_Bluetooth_controller.cfg
udev/HuiJia  USB GamePad.cfg
udev/USB_Gamepad_.cfg
udev/usb_gamepad___________(NES).cfg
udev/usb_gamepad___________(SEGA).cfg
udev/usb_gamepad___________(SNES).cfg
xinput/DragonRise_Inc.___Generic___USB__Joystick__.cfg

As we discussed in #424 we need to clean up duplicated/conflicting profiles from the repo. 
The problem with duplicated profiles is that Retroarch isn't capable of disambiguating between them, so it will choose one or the other just by chance.  
The goal of this PR is to keep just one set of the duplicated profiles enabled, commenting `input_device`, `input_vendor_id`, and `input_product_id` lines to disable those profiles.
cc @hizzlekizzle

Disable conflicting (duplicated) profiles

---

.travis.yml
verify_duplicate_profiles.rb

I've been working on a script to automatically detect duplicate profiles when somebody creates a Pull Request. The goal behind this is to avoid future conflicts without having to ask reviewers to manually scan all the profiles in the repository to confirm there aren't duplicates present.
This PR includes:
- Ruby script that scans the whole repository looking for duplicates
- [Travis CI](https://travis-ci.com/) configuration
Travis CI is a cloud-based continuous integration tool that can be used to automatically build software projects. They provide a free plan for open-source projects, so we can take advantage of that at no cost.
They provide a "GitHub App" integration that is really easy to setup. I don't have permissions to set up the integration in this repo so that must be performed …

Add automatic check for duplicate profiles

---

dinput/SQONYY_gamepad.cfg

Apparently the current state causes up to be pressed continuously. Fix has been verified by Zaion on the retroachievements discord.

Fix stick axis in dinput SQONYY_gamepad.cfg

---

android/Sony Interactive Entertainment Wireless Controller.cfg

The profile is used by both wired and wireless Dualshock 4 V2's

Remove (wired) appendix from profile name

---

android/Google_Nexus_Controller.cfg

D-pad up is missing when I use my Nexus Gamepad, and this looks like why. It's untested, as I don't know how to test a gamepad config in unrooted Android without getting a whole build environment up, but this change looks like it can't cause harm, and the current config is definitely broken.

Add d-pad up to the Google Nexus Gamepad config

---

android/NVIDIA_SHIELD_2019_Remote.cfg

This PR adds a profile for the NVIDIA SHIELD 2019 Remote, which comes with the NVIDIA SHIELD 2019 Pro and the regular "tube" version. The remote can be purchased separatedly as well.
Because it's a TV-like remote, the mappings are a bit limited but fully functional to navigate the RetroArch interface and use in cores with at most two buttons, e.g. NES or MegaDrive:
| Remote Button | RetroPad Button |
|:--|:--|
| Center | A button |
| Back | B button |
| Play/Pause | Start button |
| Fast Forward | Select button |
| Up | D-Pad Up |
| Down | D-Pad Down |
| Left | D-Pad Left |
| Right | D-Pad Right |
| Rewind | Menu toggle button |
> **Note:** Buttons in the remote that are not in the above table are not assignable, e.g. Mic, Home, Volume Up/Down, etc. :(
Tested on real hardware.

Added NVIDIA SHIELD 2019 Remote

---

udev/Honey Bee QuasiCON.cfg

Added autoconfig file for Quasicon 2P Arcade Controller (udev)
- default setup for all buttons
- labels for buttons and axis

Add Quasicon 2P Arcade Control (udev)

---

udev/QanBa_Q4RAF_Arcade_Stick.cfg

The mapping I got for this controller was incorrect so here is the mapping I created and have been playing with for a few months.
I believe the `ACRUX_QuanBa_Arcade_JoyStick_1008.cfg` is incorrect in calling device `3888:4352` a Q4RAF, I think it's actually a Q1-W 2-in-1 which is quite different.
I can remove the comment or change the name in other config as required.

Add Qanba Q4RAF arcade stick

---

.gitlab-ci.yml

This PR adds a `.gitlab-ci.yml` file, required for packaging jobs on the new infrastructure.

Add .gitlab-ci.yml file

---

dinput/Logitech_RumblePad_2.cfg
dinput/Mayflash_USB_Adapter.cfg
dinput/Microsoft_Sidewinder_Game_Pad_USB.cfg

I don't even think it breaks anything by leaving these to "winxinput", but let's make it clean! :)

3 dinput profiles had "winxinput" as "input_driver".

---

xinput/8Bitdo_N30_Modkit_BT.cfg

This profile conflicts with real Xbox One controllers, leaving over half the controller unmapped in the process. The 8bitdo N30 Modkit supports dinput, so an xinput profile isn't even necessary. I've left the profile disabled rather than removing it in case we have a more elegant way to differentiate in the future, but for now this seems like a necessary change.

Disable xinput profile for 8bitdo N30 Modkit

---

dinput/8Bitdo_M30_BT.cfg

The 8Bitdo M30 autoconf profile currently in the repo has counter-intuitive mappings.
One could argue the use case for this 6 face button controller is primarily MD/Gen/Saturn. However the current profile is mapped after the standard SNES layout. This can be confusing for new users. The issue was discussed on the forums [here](https://forums.libretro.com/t/8bitdo-m30-w-retroarch/21175) and [there](https://forums.libretro.com/t/problem-assigning-autoconfig-values-to-m30-bluetooth-controller/30656) among others and solved by @hunterk and SirBedwyr.
This corrected profile makes the MD/Gen experience plug & play (and remaps for other systems much less confusing).
- corrected layout as LXR/YBA
- renamed "MODE" as "Minus (-)" to reflect the actual name of the button on the controller
- added …

fix for 8Bitdo M30 Bluetooth controller layout

---

hid/Elecom_JC-W01U.cfg

- Elecom JC-W01U Wii USB Gamepad Converter ([web link](https://www.elecom.co.jp.e.gj.hp.transer.com/products/JC-W01UWH.html))
- mapped buttons for official SNES/SFC Wii Controller

Add Elecom JC-W01U Wii USB Gamepad Converter for hid

---

udev/Sony-PlayStation4-DualShock4-Controller.cfg

See additional comments on https://github.com/libretro/retroarch-joypad-autoconfig/commit/336f2a563f267bffe40600361cd124c0564f9f79

fix ds4v1 support on "modern" linux distros

---

hid/Retrode_2.cfg

Tested on Wii and Wii U.
I provided dinput and udev files already some years ago.

Add Retrode 2 USB adapter

---

dinput/8Bitdo_SN30_GP_BT.cfg

Change 8Bitdo SN30 GP BT file to add Analog inputs when using respective modes (Select + Left, Up and Right for Left Analog, D-Pad and Right Analog respectively) Also change default input axis to hat, as default input mode is D-Pad (Which is not an Axis)

Analog inputs plus correct default d-pad inputs

---

android/Onn-Remote.cfg

Ready to be merged, brings support on board for Walmart's Onn 4k streamer Part No 100026240.
https://www.walmart.com/ip/onn-Android-TV-4K-UHD-Streaming-Device-with-Voice-Remote-Control-HDMI-Cable/636597403
Also to note - I had to flip the values for b and a from what the default Android TV cfg had, but it seems to be working fine now. Also reset my controllers configs just to make sure I had no active remaps happening on top of the default config.
What the values are now
```
input_b_btn = "23"
input_a_btn = "4"
```
~~Work in progress.. the D-Pad controls appear to work fine, but select and back appear to be non-functional at the moment. Creating this PR however for additional visibility to the problem. Also inclusion may still be warranted as partial support is better than no support and …

Adds Onn Remote support for menu navigation

---

dinput/raphnet-tech_1-player_WUSBMote_v2.2.cfg

Changes:
1) Changed version from v2.1 to v2.2 because RetroArch wouldn't detect the adapter without this change.
2) Added a mapping for the Wii Classic controller's Home button.

Update Raphnet 1-player WUSBMote to v2.2

---

udev/Nintendo Switch Right Joy-Con.cfg

Update Nintendo Switch Right Joy-Con.cfg

---

udev/Nintendo - Switch Pro Controller.cfg

It appears this will be included in the Linux kernel beginning with version 5.16 (https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.16).

Update Nintendo - Switch Pro Controller.cfg

---

sdl2/8BitDo_Ultimate_C_Wired_Controller.cfg
udev/8BitDo_Ultimate_C_Wired_Controller.cfg
udev/8BitDo_Ultimate_C_Wired_Controller_DInput.cfg

Both udev and sdl2 config files are provided. The sdl2 config is particularly useful for the Retroarch Flatpak, which uses the sdl2 driver by default.
I do not have a Windows license, so this is Linux support only.

Add support for the 8BitDo Ultimate C Wired controller in X-Input mode.

---

Makefile

This fixes warnings that often happened on make install via Lakka.
```
<<< retroarch_joypad_autoconfig:target seq 11 <<<
sha256sum: packages/lakka/retroarch_base/retroarch_joypad_autoconfig/joypad_configs/udev/Nintendo: No such file or directory
sha256sum: Switch: No such file or directory
sha256sum: Left: No such file or directory
sha256sum: Joy-Con.cfg: No such file or directory
sha256sum: packages/lakka/retroarch_base/retroarch_joypad_autoconfig/joypad_configs/udev/Nintendo: No such file or directory
sha256sum: Switch: No such file or directory
sha256sum: Right: No such file or directory
sha256sum: Joy-Con.cfg: No such file or directory
```

make: Clean up make install usage

---

dinput/8Bitdo_N64_Modkit.cfg

The [8BitDo N64 Modkit](https://shop.8bitdo.com/products/8bitdo-mod-kit-for-original-n64-controller) is a replacement PCB and "rumble pak" that converts an OEM N64 Controller to a USB/Bluetooth controller with two modes: one that emulates an NSO N64 controller (for which there are already autoconfig files), and the other that presents as a normal DirectInput controller with a unique PID/VID. This pull request adds a `dinput` config file for the second mode of operation.
I tried to the match the formatting of the other 8BitDo `dinput` configs, but since the controller physically offers the same buttons as the NSO N64 Controller (including addition of ZR and Home buttons), I used the same RetroPad mappings as the existing `N64_Nintendo_Switch_Online.cfg` (with DirectInput button/axis …

Add dinput config for 8BitDo N64 Modkit

---

dinput/8Bitdo_Pro_SN30_BT.cfg
dinput/8Bitdo_Pro_SN30_USB.cfg
udev/8Bitdo_Pro_SN30_BT_B.cfg
udev/8Bitdo_Pro_SN30_USB.cfg

The menu button binding for this controller (in both the Bluetooth and USB configs) is wrong. I'm not sure if it's always been wrong, or if the button mapping has changed in recent firmware, but in any case, none of the buttons on the controller map to button 2. In fact, the menu button (8BitDo "heart" logo) is button 12.
Should I also update the udev configs? They seem to use the exact same mappings as D-Input, so it might make sense, but I don't have a way of testing with udev right now.

Fix menu button bindings for 8BitDo SN30 Pro

---

xinput/8BitDo_N30_Modkit_BT.cfg

Replaced "8Bitdo" (typo for "d") with "8BitDo" (official name).

Update and rename 8Bitdo_N30_Modkit_BT.cfg to 8BitDo_N30_Modkit_BT.cfg

---

udev/PowerA_Wireless_Controller_for_Nintendo_Switch.cfg

Config file for the PowerA Wireless Controller for Nintendo SWitch Switch, SKU NSGP0012-01. Set `_label` names from [the official manual](https://www.powera.com/siteassets/user-manuals/nsw/nsw-enhanced-wireless-controller/powera-enhanced-wireless-aa-controller-switch-manual_2021_1643935539.pdf) and mapped based on the joycon config.
To the best of my knowledge and efforts, this controller doesn't advertise a USB VID or PID. However, RetroArch correctly configures the controller using `input_device`, as noted in the config file. Device tested on RetroArch as per Readme.

Add udev autoconfiguration PowerA Wireless Controller

---

sdl2/PS5 Controller.cfg

replaced
input_product_id = "1476"
with
input_product_id = "3302"
Reference:
* RetroArch Flatpak uses SDL2 by default and generated "input_product_id = "3302"" via "Settings -> Input -> Port 1 Binds -> Save Controller Profile"
* `input_product_id = "1476"` is the product ID for [PS4 Controller.cfg](https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/sdl2/PS4%20Controller.cfg).

sdl: Fix PS5 Controller Product ID

---

udev/RetroUSB-N64-RetroPort.cfg

Add mapping for [USB N64 Retroport](https://www.retrousb.com/product_info.php?cPath=21&products_id=82&osCsid=d1511c0e801bd16feddd987fb03be95f). Verified there are no conflicting vendor and product pids

udev: Add RetroUSB N64 RetroPort

---

udev/RetroUSB-N64-RetroPort.cfg

Minor update to RetroUSB N64 adapter config. The Y and X buttons are now mapped to C buttons above B and A respectively. This is a more consistent layout even though Y and X buttons are not used in N64 games. Just in case you need them.
The comment also suggest a better fix for control stick sensitivity. Sensitivity changes are kept to the Mupen64 core for the most part instead of implementing a global change for all cores

udev: Fix RetroUSB N64 Y and X buttons to be consistent with B and A button layout

---

dinput/Wireless Gamepad.cfg

Retro Fighters Brawler64 Wireless Gamepad
UPC: 850046080067
The physical B button shares 2 functions: in game, it serves as the n64 "B" button. in the retroarch menus it serves as a back button, ("A" according to port 1 control menu).  This is the best way i could figure out how to map this gamepad for nintendo 64 games. Only problem is that the "Y" button is also serves for deleting hotkeys in the menu. work around for this is to temporarily set "y" to a C up, down, left, or right button. remove the hotkey errors and then resetting to default controls afterwards in port 1 control.

[DInput] Add Retro Fighter Brawler64 support

---

sdl2/PS5 Controller.cfg

Added comments and a bug report link that L2/R2 have been manually edited due to a RetroArch bug.

sdl2: Add PS5 Controller note for L2/R2

---

udev/PowerA_Enhanced_Wired_Controller_For_Xbox_Series_X_S_Blue_Hint-xone.cfg
udev/PowerA_Enhanced_Wired_Controller_For_Xbox_Series_X_S_Blue_Hint.cfg

Full controller name: PowerA Enhanced Wired Controller for Xbox Series X|S - Blue Hint
Includes a separate autoconfig file for the `xone` driver (https://github.com/medusalix/xone)

udev: Add PowerA Xbox X/S Wired Controller

---

README.md

The document at https://github.com/libretro/docs/blob/master/docs/guides/controller-autoconfiguration.md has not been updated on the official website for an extended period. It contains more current information that can assist users in preventing errors when uploading autoconfiguration files.

docs: Fix link to documentation site

---

android/Pro Controller.cfg

Attribution occurs through project documentation and commit history, not contributor graffiti

docs: Clean up some documenation

---

sdl2/DragonRise Inc. GameCube Controller Adapter.cfg

This is a Generic Brand-less GameCube Controller Adapter.
Unfortunately the axes don't go up to 1.0 on max input, and per-axis/per-controller sensitivity is not supported in the file, so a recommendation for global sensitivity is added as a comment.
There's also a description of what this adapter looks like, and the model number.
See:
- #912

sdl2: Add DragonRise Inc. GameCube Controller Adapter

---

udev/Thrustmaster FGT Rumble 3-in-1.cfg

Label for A button is wrong. Was duplicate of B/Down button but should be "Right".

Update Thrustmaster FGT Rumble 3-in-1.cfg - fix A button label
