libretro/retroarch-joypad-autoconfig

- udev/Saitek_PLC_P2600_Rumble_Force_Pad.cfg
VID : 0x06a3
PID: 0xff0d
Signed-off-by: XoD <xoddark@gmail.com>
> Add Vendor ID and Product ID for Saitek P2600

- udev/DAP_8Bitdo_NES30_PRO.cfg
Signed-off-by: XoD <xoddark@gmail.com>
> Add forgotten vid:pid for NES30PRO.

- android/Mojo_Retro_Adapter_Mod.cfg
Filename and device_name were wrong. Tested using bind all and save autoconfig.
> Replace Retro_Adapter_Mod.cfg with Mojo_Retro_Adapter_Mod.cfg

- udev/HORI CO.,LTD. Fighting Commander 4.cfg
I've tested this with Street Fighter II: Championship Edition and with Golden Axe, both using the Genesis Plus GX core.
> udev autoconfig for HORI Fighting Commander 4

- udev/HORI CO.,LTD. Fighting Commander 4.cfg
Button labels added, as requested.
> Button labels and menu key for HORI Fighting Commander 4

- android/Nvidia Shield Virtual Controller.cfg
This profile handles input received from CEC remotes.
Will make a pull request for Retroarch that enables this as an input device.
> Add Nvidia Shield Virtual Controller profile

- xinput/Sega_Joypad_Adapter_v3.0.cfg
> Add Retronic Design USB joystick adapter for Sega Genesis/Megadrive joypad

- udev/VenomLimitedPS3PS4ArcadeJoystick.cfg
Sorry, missed this step out before!
> Updated Venom PS3/4 Fightstick with VID/PID

- udev/8Bitdo_SNES30_GamePad.cfg
Updated 8Bitdo SNES GamePad. In this new version of the firmware, the directional functions as axes.
> Updated 8Bitdo SNES config, latest firmware.

- udev/usb_gamepad___________(NES).cfg
- udev/usb_gamepad___________(SNES).cfg
These controllers share the same USB ID but have different button
configurations.
> Added generic NES and SNES like USB controllers

- udev/DragonRise_Inc.___Generic___USB__Joystick__.cfg
Added a display_name
Changed a few button names
Modified comments
> udev: minor updates to DragonRise 0079:0006

- udev/Xtreme_Morpheus.cfg
Automatic configuration for Xtreme Morpheus joypad (USB, wired)
> Added Xtreme Morpheus joypad

- udev/Sony-PlayStation4-DualShock4-Controller-Bluetooth.cfg
Reverts libretro/retroarch-joypad-autoconfig#349
> Revert "Revert "Fixes faulty DS4 wired linux profile and adds bluetooth linux profile""

- android/8Bitdo_Arcade_N30_BT.cfg
- android/8Bitdo_Arcade_N30_USB.cfg
- udev/8Bitdo_Arcade_N30_BT.cfg
- udev/8Bitdo_Arcade_N30_USB.cfg
- xinput/8Bitdo_Arcade_N30_BT.cfg
- xinput/8Bitdo_Arcade_N30_USB.cfg
> 8Bitdo N30 Arcade Firmware v4.01

- hid/8Bitdo_Pro_SF30_USB.cfg
Tested on macOS via USB on Android mode
> hid: Add 8Bitdo SF30 Pro

- udev/raphnet.net_4nes4snes.cfg
Product ID was wrong with firmware 1.5 and mapping was incomplete.
> Update raphnet.net_4nes4snes.cfg 

- xinput/8Bitdo_MD30_Modkit_BT.cfg
- xinput/8Bitdo_MD30_Modkit_USB.cfg
- xinput/8Bitdo_N30_Modkit_BT.cfg
- xinput/8Bitdo_SN30_Modkit_BT.cfg
MD30 is the only USB config because it's the only controller with an exposed USB port.
> Adding 8Bitdo modkit configs.

- udev/3H Dual Arcade.cfg
Autoconfig for a JAMMA to USB input adapter board
> Create autoconfig for 3h dual arcade jamma to usb adapter

- udev/SNES PC Game Pad    SNES PC Game Pad   .cfg
Adding autoconfig for tomee snes usb dongle
> Create SNES PC Game Pad    SNES PC Game Pad   .cfg

- android/8Bitdo_M30_BT.cfg
Add Android support for 8Bitdo M30 Bluetooth controller.
> Add Android support for 8Bitdo M30 Bluetooth controller

- udev/ELECOM JC-U4113S DirectInput Mode.cfg
- udev/ELECOM JC-U4113S XInput Mode.cfg
Tested on Debian Unstable with Retroarch 1.7.5.
> Autoconfig for ELECOM JC-U4113S gamepad.

- udev/usb_gamepad___________(PS1).cfg
This is a Playstation style gamepad that uses a generic chinese USB gamepad encoder chip common in other gamepads with different button configurations.
> Playstation classic like chinese gamepad

- xinput/8Bitdo_M30_BT.cfg
- xinput/8Bitdo_M30_USB.cfg
Configs include hat, left joystick, and right joystick associations for D-Pad.
> Added xinput autoconfigs for 8Bitdo M30 controller

- udev/Gametel_Bluetooth_controller.cfg
This is an autoconfig file for my Gametel Bluetooth controller (www.gametel.se).
> Autoconfig file for Gametel Bluetooth controller

- udev/Wireless Steam Controller.cfg
all details in comments of the config file
> Add Wireless Steam Controller udev config

- udev/MOSIC______SPEED-LINK_Competition_Pro_.cfg
A bit more human readable input_device_display_name
> Human friendly display name

- udev/odroidgo2_joypad_v11.cfg
These have been tested on my oga 1.1 unit
> Add mappings for odroidgo2 v1.1

- udev/HORI_Real_Arcade_Pro_V.cfg
https://hori.co.uk/real-arcade-pro-v-hayabusa-for-nintendo-switch
> add udev HORI RAP.V (Nintendo Switch)

- udev/8Bitdo_P30_Modkit_BT.cfg
- xinput/8Bitdo_N30_Modkit_BT.cfg
> Add 8Bitdo Modkits

- android/8BitDo_Pro2_BT.cfg
- android/8BitDo_Pro2_USB.cfg
- dinput/8BitDo_Pro2_BT.cfg
- dinput/8BitDo_Pro2_USB.cfg
- hid/8BitDo_Pro2_BT.cfg
- hid/8BitDo_Pro2_USB.cfg
The hid configuration is generated on my Mac computer, I am not sure whether to use'hid' or'iohidmanager', at least it works on my MacBook Pro.
> Added 8BitDo Pro 2 gamepad

- android/8BitDo_SN30_Pro+_BT.cfg
- android/8BitDo_SN30_Pro+_USB.cfg
- android/8Bitdo_Pro_SF30_BT.cfg
- android/8Bitdo_Pro_SF30_USB.cfg
- android/8Bitdo_Pro_SN30_BT.cfg
- android/8Bitdo_Pro_SN30_USB.cfg
The home button in the new firmware has been adjusted to conform to the Android system home.
> Fixed the Home button keycode

- android/Infra-Red.cfg
- android/Telecomando TIM v2.cfg
Added configuration for Infrared and Bluetooth mode, only for menu navigation
> Add TimBox remote control for Android

- android/8BitDo_Pro2_updatedFW.cfg
- dinput/8BitDo_Pro2_updatedFW.cfg
based on previous configs
plus i got the triggers to be analog on android (not possible on windows due to driver differences)
hid driver just doesn't seem to work at all on any of my devices and i don't have a mac so i didn't bother
tested and ready for merge, but i might add some more drivers
> android/dinput configs for 8BitDo Pro 2's new PID

- udev/8BitDo_Pro2_BT_X.cfg
I had some issues with my 8BitDo Pro 2 controller getting recognized as a 8BitDo M30 controller in RetroArch, so I decided to make a proper file to map this device. I hope it helps!
> Add 8BitDo Pro 2 udev config

- udev/Flydigi Vader 2 Pro.cfg
- udev/Flydigi Vader 2.cfg
Add Gamepad "Flydigi Vader 2" and "Flydigi Vader 2 Pro" bluetooth connetion profile
> Create "Flydigi Vader 2.cfg" and "Flydigi Vader 2 Pro.cfg"

- android/8Bitdo_M30_24G.cfg
- dinput/8Bitdo_M30_24G.cfg
> Add 8Bitdo M30 2.4G (Android, Dinput)

- udev/8BitDo_NEOGEO_24G.cfg
- udev/8BitDo_NEOGEO_BT.cfg
I created this config in order to make my new 8BitDo NEOGEO controller work with RetroArch on linux system, specifically JELOS on retro handheld console Powkiddy RGB30.
> Add 8BitDo NEOGEO Wireless Controller in 2.4g and Bluetooth (udev)

- dinput/Thrustmaster FGT Rumble 3-in-1.cfg
New wheel. Use two modes (combined and separated) for left pedal. You can configurated both modes in Retroarch.
> Add Thrustmaster FGT Rumble 3-in-1 (DInput)

- xinput/Controller (Ultimate Wireless Controller).cfg
8bitdo Ultimate Bluetooth Controller
UPC: 6922621502487
Basic setup for pretty much any left and right joystick controller. this one has a nice charging dock.
> [XInput] Add 8bitdo Ultimate Bluetooth Controller Support

- dinput/Wireless Gamepad.cfg
> dinput: Fix Brawler64 config matching Switch Pro Controllers

- udev/8BitDo_Ultimate_2C_Wireless_Wired_Mode.cfg
I made a config file for 8Bitdo Ultimate 2C Wireless in Wired Mode.
> udev: Add 8Bitdo Ultimate 2C Wireless in Wired Mode

- dinput/8BitDo_Ultimate_2C_Wireless_Controller_BT.cfg
8BitDo Ultimate 2C Wireless Controller Bluetooth profile, so you can use without the usb dongle.
> dinput: Add 8BitDo Ultimate 2C Wireless Controller BT

- dinput/8BitDo_Ultimate_2_Wireless_Controller_BT.cfg
8BitDo Ultimate 2 Wireless Controller Bluetooth profile, so you can use without the usb dongle.
> dinput: Add 8BitDo Ultimate 2 Wireless Controller BT

- dinput/8Bitdo_M30_USB.cfg
> dinput: Fix 8Bitdo M30 USB menu toggle

- dinput/8Bitdo_M30_BT.cfg
> dinput: Fix 8Bitdo M30 BT menu toggle
